# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [4]:
np.__version__,np.show_config

('1.17.0', <function numpy.__config__.show()>)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [6]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [9]:
print(a.size)
print(a.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [11]:
np.info(np.sum)

 sum(*args, **kwargs)

Sum of array elements over a given axis.

Parameters
----------
a : array_like
    Elements to sum.
axis : None or int or tuple of ints, optional
    Axis or axes along which a sum is performed.  The default,
    axis=None, will sum all of the elements of the input array.  If
    axis is negative it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If axis is a tuple of ints, a sum is performed on all of the axes
    specified in the tuple instead of a single axis or all the axes as
    before.
dtype : dtype, optional
    The type of the returned array and of the accumulator in which the
    elements are summed.  The dtype of `a` is used by default unless `a`
    has an integer dtype of less precision than the default platform
    integer.  In that case, if `a` is signed then the platform integer
    is used while if `a` is unsigned then an unsigned integer of the
    same precision as the platform integer is used.
out : ndarray, optional


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [12]:
b=np.arange(1,11)
print(b)
b[4]=1
b

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3,  4,  1,  6,  7,  8,  9, 10])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [13]:
c=np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [14]:
c[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [15]:
d=np.arange(0,9).reshape(3,3)
d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [16]:
e=[1,2,0,0,4,0]
np.nonzero(e)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [19]:
np.random.random((3,3,3))

array([[[0.22174977, 0.88392058, 0.91042943],
        [0.28848462, 0.13967828, 0.91584674],
        [0.24220556, 0.20945515, 0.67618693]],

       [[0.90992657, 0.72363649, 0.31146993],
        [0.7621614 , 0.08328478, 0.8188434 ],
        [0.71787565, 0.68627076, 0.29028022]],

       [[0.70700338, 0.94643828, 0.567922  ],
        [0.81245392, 0.9771941 , 0.24811865],
        [0.6710536 , 0.37401811, 0.18563778]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [20]:
e=np.random.random((10,10))
print(e)
print(e.min(),e.max())

[[0.64576456 0.58681011 0.37348674 0.97048689 0.17627105 0.55994479
  0.86241979 0.87525468 0.36609249 0.33203278]
 [0.23082527 0.80606044 0.47720878 0.95673146 0.02093918 0.1438214
  0.09450737 0.19216788 0.91536103 0.3401914 ]
 [0.54636127 0.37808224 0.23554425 0.12512984 0.6169474  0.91381128
  0.04241733 0.24071434 0.62552339 0.03033363]
 [0.15811922 0.97552369 0.01794177 0.9405345  0.5406871  0.75270809
  0.96793695 0.90340184 0.33947698 0.94107573]
 [0.82031977 0.80230403 0.60237913 0.46916946 0.10648459 0.60119435
  0.45299963 0.53965949 0.08297831 0.7834772 ]
 [0.93249295 0.70115997 0.52571369 0.15503062 0.67179894 0.25551081
  0.72143024 0.87908435 0.08294387 0.76741974]
 [0.44285794 0.36582642 0.51590401 0.88016515 0.27855317 0.27736557
  0.57149708 0.92756151 0.10790375 0.94795063]
 [0.62643494 0.07502078 0.21918583 0.0586997  0.0106513  0.7023003
  0.24820793 0.61593298 0.05982137 0.32552368]
 [0.6121654  0.28846503 0.21463466 0.33793515 0.37611428 0.4204425
  0.63511823 0.

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [21]:
f=np.random.random(30)
f.mean()

0.4559426819778905

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [22]:
g=np.ones((5,5))
print(g)
g[1:-1,1:-1]=0
g

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [23]:
print(g)
np.pad(g,pad_width=2,mode="constant",constant_values=0)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [24]:
print(0*np.nan)
print(np.nan==np.nan)
print(np.inf>np.nan)
print(np.nan-np.nan)
print(0.3==3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [25]:
np.diag([1,2,3,4],k=-1)


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [26]:
g=np.ones((8,8))
g[1::2,::2]=0
g[::2,1::2]=0
g

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [27]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [28]:
np.tile(np.array([[0,1],[1,0]]),(4,4))


array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [29]:
x=np.random.random((5,5))
print(x)
(x-x.min())/(x.max()-x.max())

[[0.98642549 0.32516853 0.00583498 0.41844429 0.93016422]
 [0.28466345 0.7473657  0.33767198 0.78918034 0.00778712]
 [0.55382981 0.81184934 0.14397341 0.02533276 0.52614173]
 [0.86362752 0.33039299 0.83740267 0.3298564  0.0023704 ]
 [0.30158108 0.29281171 0.14463492 0.49414533 0.77888074]]


D:\Applications\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
D:\Applications\Anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, nan],
       [inf, inf, inf, inf, inf]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [30]:
RGBA = np.dtype([('r',np.uint8),('g',np.uint8),('b',np.uint8),('a',np.uint8)])
color = np.array((1,2,3,4),dtype = RGBA)
print(color['a'])
type(color)

4


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [31]:
x=np.random.random((5,3))
y=np.random.random((3,2))
np.dot(x,y)

array([[0.65006286, 0.24335631],
       [1.89007627, 0.90398746],
       [0.66922479, 0.3090131 ],
       [1.26629078, 0.62565916],
       [1.42562011, 0.63564014]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [32]:
m=np.arange(1,11)
print(m)
m[(3<m)&(m<8)]*=-1
m

[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [33]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
z=arange(1,10)
print(z**z)
print(2<<z<<2)
print(z<-z)
print(1j*z)
print(z/1/1)
# print(z<z<z)

[        1         4        27       256      3125     46656    823543
  16777216 387420489]
[  16   32   64  128  256  512 1024 2048 4096]
[False False False False False False False False False]
[0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [35]:
np.array(0)/np.array(0)
np.array(0)//np.array(0)
np.array([np.nan]).astype(int).astype(float)

D:\Applications\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\Applications\Anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [36]:
j=np.random.uniform(-8,8,5)
print(j)
np.copysign(j,+2)
np.abs(j)
np.ceil(j)#round

[ 3.25892703  6.18230055 -7.89549083 -3.48268121  3.27162955]


array([ 4.,  7., -7., -3.,  4.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [37]:
k=np.arange(1,10)
l=np.arange(6,15)
np.intersect1d(k,l)

array([6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [38]:
print(np.seterr())
np.errstate()

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [39]:
np.sqrt(-1) == np.emath.sqrt(-1)


D:\Applications\Anaconda\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [41]:
y = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ",y)
t     = np.datetime64('today', 'D')
print("Today: ",t)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yesterday:  2022-05-28
Today:  2022-05-29
Tomorrow:  2022-05-30


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [42]:
np.arange("2016-07","2016-08",dtype='datetime64[D]')


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [43]:
p=np.ones(3)*2
q=np.ones(3)*3
np.multiply((np.add(p,q)),np.divide(np.negative(p),2))

array([-5., -5., -5.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [44]:
o=np.linspace(1,10,5)
print(o)
print(o-o%2)
print(np.floor(o))
print(np.ceil(o))
print(np.trunc(o))
print(o.astype(complex))

[ 1.    3.25  5.5   7.75 10.  ]
[ 0.  2.  4.  6. 10.]
[ 1.  3.  5.  7. 10.]
[ 1.  4.  6.  8. 10.]
[ 1.  3.  5.  7. 10.]
[ 1.  +0.j  3.25+0.j  5.5 +0.j  7.75+0.j 10.  +0.j]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [45]:
s=np.tile(np.arange(0,5),(5,1))
print(s)
s.shape

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


(5, 5)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [46]:
def generator():
  for i in range(0,10):
        yield i
np.fromiter(generator(),dtype=int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [47]:
np.linspace(0,1,12,endpoint=True)[1:-1]


array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [48]:
rv=np.random.randint(20,size=10)
rv.sort()
s

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [49]:
np.add.reduce(np.arange(27).reshape((3,3,3)),0)


array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [50]:
A=np.random.randint(10,20,5)
B=np.random.randint(10,20,5)
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [51]:
z=np.arange(0,10)
print(z)
z.flags.writeable=False
z

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [52]:
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]
r=np.sqrt(x**2 + y**2)
Deg=np.arctan2(y,x)
print(r)
print(Deg)

[0.95382575 0.61044686 0.52928956 0.73417569 1.02559378 0.51428152
 1.03601644 1.10952111 0.29707455 0.71356601]
[0.37713025 0.01497439 0.74295739 0.25178642 1.32804488 1.04690554
 0.65319219 1.03228304 0.10109559 0.95068058]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [53]:
m=np.random.randint(10,30,10)
print(m)
m[argmax(m)]=0
m

[14 13 19 29 16 22 11 28 13 23]


array([14, 13, 19,  0, 16, 22, 11, 28, 13, 23])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [54]:
Z = np.ones((5,5), [('x',int),('y',int)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 0) (0, 0) (0, 0) (0, 0) (1, 0)]
 [(0, 1) (0, 1) (0, 1) (0, 1) (1, 1)]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [55]:
X = np.arange(1,5).reshape(2,2)
print(X)
Y = np.arange(5,9).reshape(2,2)
print(Y)
C = (1/(np.subtract.outer(X,Y)))
C

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


array([[[[-0.25      , -0.2       ],
         [-0.16666667, -0.14285714]],

        [[-0.33333333, -0.25      ],
         [-0.2       , -0.16666667]]],


       [[[-0.5       , -0.33333333],
         [-0.25      , -0.2       ]],

        [[-1.        , -0.5       ],
         [-0.33333333, -0.25      ]]]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [56]:
for dtype in [np.int8,np.int16, np.int32, np.int64]:
   print(np.iinfo(dtype).min,np.iinfo(dtype).max)
for dtype in [np.float16,np.float32, np.float64]:
   print(np.finfo(dtype).min,np.finfo(dtype).max,np.finfo(dtype).eps)

-128 127
-32768 32767
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-65500.0 65500.0 0.000977
-3.4028235e+38 3.4028235e+38 1.1920929e-07
-1.7976931348623157e+308 1.7976931348623157e+308 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [57]:
np.set_printoptions(precision=2,threshold=None)
C

array([[[[-0.25, -0.2 ],
         [-0.17, -0.14]],

        [[-0.33, -0.25],
         [-0.2 , -0.17]]],


       [[[-0.5 , -0.33],
         [-0.25, -0.2 ]],

        [[-1.  , -0.5 ],
         [-0.33, -0.25]]]])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [58]:
c=np.arange(100)
d=np.random.uniform(0,100)
print(d)
index=(np.abs(c-d)).argmin()
print(c[index])

5.217981766733326
5


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [59]:
np.ones(10,[('position',[('x',float,1),
                            ('y',float,1)]),
               ('color',[('r',float,1),
                         ('g',float,1),
                         ('b',float,1)])])

D:\Applications\Anaconda\lib\site-packages\numpy\core\numeric.py:214: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


array([((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.)),
       ((1., 1.), (1., 1., 1.)), ((1., 1.), (1., 1., 1.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [60]:
rv=np.random.random((100,2))
x,y=np.atleast_2d(rv[:,0],rv[:,1])
d=np.sqrt((x-x.T)**2 +(y-y.T)**2)
print(d)

[[0.   0.11 0.37 ... 0.34 0.7  0.64]
 [0.11 0.   0.46 ... 0.25 0.81 0.75]
 [0.37 0.46 0.   ... 0.6  0.55 0.51]
 ...
 [0.34 0.25 0.6  ... 0.   1.04 0.98]
 [0.7  0.81 0.55 ... 1.04 0.   0.07]
 [0.64 0.75 0.51 ... 0.98 0.07 0.  ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [63]:
a=np.arange(5, dtype=np.float32)
b=a.astype(np.int32,copy=False)
print(a)
print(b)

[0. 1. 2. 3. 4.]
[0 1 2 3 4]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [64]:
from io import StringIO
f=StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
z=np.genfromtxt(f, delimiter=",", dtype=int,missing_values=0)
print(z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [65]:
e=np.arange(8).reshape(2,2,2)
for index,value in np.ndenumerate(e):
    print(index, value)
for index in np.ndindex(e.shape):
    print(index, e[index])

(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7
(0, 0, 0) 0
(0, 0, 1) 1
(0, 1, 0) 2
(0, 1, 1) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 1, 0) 6
(1, 1, 1) 7


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [66]:
x,y=np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d=np.sqrt(x*x+y*y)
sigma,mu=1.0, 0.0
g=np.exp(-((d-mu)**2/(2.0*sigma**2)))
print(g)

[[0.37 0.45 0.52 0.57 0.6  0.6  0.57 0.52 0.45 0.37]
 [0.45 0.55 0.63 0.7  0.73 0.73 0.7  0.63 0.55 0.45]
 [0.52 0.63 0.73 0.81 0.85 0.85 0.81 0.73 0.63 0.52]
 [0.57 0.7  0.81 0.89 0.94 0.94 0.89 0.81 0.7  0.57]
 [0.6  0.73 0.85 0.94 0.99 0.99 0.94 0.85 0.73 0.6 ]
 [0.6  0.73 0.85 0.94 0.99 0.99 0.94 0.85 0.73 0.6 ]
 [0.57 0.7  0.81 0.89 0.94 0.94 0.89 0.81 0.7  0.57]
 [0.52 0.63 0.73 0.81 0.85 0.85 0.81 0.73 0.63 0.52]
 [0.45 0.55 0.63 0.7  0.73 0.73 0.7  0.63 0.55 0.45]
 [0.37 0.45 0.52 0.57 0.6  0.6  0.57 0.52 0.45 0.37]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [67]:
n=4
p=3
z=np.zeros((n,n))
np.put(z,np.random.choice(arange(n*n), p, replace=False),1)
print(z)

[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [68]:
x=np.random.rand(5,5)
print(x)
y=x-x.mean(axis=1, keepdims=True)
# y=x-x.mean(axis=1).reshape(-1, 1)
print(y)

[[0.79 0.51 0.02 0.26 0.38]
 [0.68 0.38 0.4  0.66 0.66]
 [0.15 0.49 0.17 0.86 0.44]
 [0.48 0.   0.44 0.17 0.54]
 [0.89 0.32 0.72 0.15 0.95]]
[[ 0.39  0.12 -0.37 -0.13 -0.01]
 [ 0.12 -0.17 -0.16  0.1   0.11]
 [-0.27  0.07 -0.25  0.44  0.02]
 [ 0.15 -0.32  0.11 -0.15  0.21]
 [ 0.28 -0.28  0.12 -0.46  0.34]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [69]:
z=np.random.randint(0,10,(3,3))
print(z)
print(z[z[:,1].argsort()])

[[3 3 3]
 [1 1 0]
 [2 8 1]]
[[1 1 0]
 [3 3 3]
 [2 8 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [70]:
Z=np.random.randint(0,3,(3,3))
print(Z)
print((~Z.any(axis=1)).any())

[[1 2 0]
 [2 1 0]
 [2 0 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [71]:
f=np.random.randint(0,15,(3,3))
print(f)
g=2
h=np.abs(g-f)
print(h)
i=np.argmin(h)
print(i)
k=f.flat[i]
k

[[13  2 11]
 [ 6  8 13]
 [ 7  1  0]]
[[11  0  9]
 [ 4  6 11]
 [ 5  1  2]]
1


2

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [72]:
A=np.arange(3).reshape(3,1)
print(A)
B=np.arange(3).reshape(1,3)
print(B)
it=np.nditer([A,B,None])
print(it)
for x,y,z in it:
  z[...]=x+y
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [73]:
class Array(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        print(type(obj))
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
z= Array(np.arange(10), "range_of_10")
print(z.name)

<class '__main__.Array'>
range_of_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [74]:
a=np.ones(10)
b=np.random.randint(0,len(a),10)
a+=np.bincount(b,minlength=len(a))
print(a)
np.add.at(a,b,1)
print(a)

[1. 3. 2. 3. 1. 3. 2. 3. 1. 1.]
[1. 5. 3. 5. 1. 5. 3. 5. 1. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [75]:
a=[2,4,6,8,10,12]
b=[1,3,5,7,9,11]
np.bincount(a,b)

array([ 0.,  0.,  1.,  0.,  3.,  0.,  5.,  0.,  7.,  0.,  9.,  0., 11.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [76]:
w,h=16,16
i=np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
f=i[...,0]*(256*256)+i[...,1]*256+i[...,2]
n=len(np.unique(f))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [77]:
a = np.random.randint(0,10,(3,4,3,4))
sum = a.sum(axis=(-2,-1))
print(sum)
sum = a.reshape(a.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[31 54 56 51]
 [61 42 61 66]
 [67 49 50 66]]
[[31 54 56 51]
 [61 42 61 66]
 [67 49 50 66]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [78]:
D=np.random.uniform(0,1,100)
S=np.random.randint(1,10,100)
D_sum=np.bincount(S, weights=D)
D_count=np.bincount(S)
D_mean=D_sum/D_count
print(D_mean)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

D:\Applications\Anaconda\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in true_divide
  """


[ nan 0.61 0.54 0.58 0.51 0.32 0.31 0.71 0.41 0.58]
1    0.613337
2    0.541948
3    0.575860
4    0.506921
5    0.319037
6    0.314045
7    0.706614
8    0.409111
9    0.577280
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [79]:
a=np.random.randint(0,7,(2,2))
b=np.random.randint(0,10,(2,2))
np.diag(np.dot(a,b))

array([25, 42])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [80]:
v=np.array([1,2,3,4,5])
zn=3
x=np.zeros(len(v)+(len(v)-1)*zn)
x[::zn+1]=v
x

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [81]:
a=np.random.randint(1,10,(5,5,3))
b=np.random.randint(1,10,(5,5))
print(a*b[:,:,None])

[[[24  9 27]
  [ 7  4  4]
  [12 24 24]
  [24 36 12]
  [21 21  6]]

 [[18 21  6]
  [ 2  6  4]
  [24 16 12]
  [45 45 36]
  [56 56 56]]

 [[42 56 49]
  [45 35 45]
  [30 42 30]
  [72 40 48]
  [63 36 27]]

 [[45 63 54]
  [45 36 72]
  [15 35 45]
  [ 2  8  4]
  [72  9 27]]

 [[24 48 42]
  [10  2 18]
  [16  8 16]
  [12 42 54]
  [72 32 24]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [82]:
a=np.random.randint(1,5,(4,4))
print(a)
a[[0,1]]=a[[1,0]]
a

[[2 2 2 1]
 [2 3 2 3]
 [2 4 2 2]
 [2 2 2 3]]


array([[2, 3, 2, 3],
       [2, 2, 2, 1],
       [2, 4, 2, 2],
       [2, 2, 2, 3]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [83]:
faces=np.random.randint(0,100,(10,3))
f=np.roll(faces.repeat(2,axis=1),-1,axis=1)
f=f.reshape(len(f)*3,2)
F=np.sort(f,axis=1)
g=f.view(dtype=[('p0',f.dtype),('p1',f.dtype)] )
g=np.unique(g)
print(g)

[( 2, 62) ( 5, 99) ( 6, 90) ( 7, 46) (10, 66) (12, 25) (14, 63) (21, 38)
 (22,  6) (25, 33) (28,  5) (33, 12) (34, 45) (35,  7) (35, 14) (38, 97)
 (39, 10) (44, 90) (45, 60) (46, 35) (52,  2) (60, 34) (62, 52) (63, 35)
 (63, 44) (66, 39) (90, 22) (90, 63) (97, 21) (99, 28)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [84]:
a=np.bincount([1,3,5,7,10,2,4])
b=np.repeat(np.arange(len(a)),a)
print(b)

[ 1  2  3  4  5  7 10]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [85]:
def moving_average(a,n=3) :
    ret=np.cumsum(a, dtype=float)
    ret[n:]=ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a=np.arange(20)
moving_average(a)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [86]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape=(a.size - window + 1, window)
    strides=(a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z=rolling(np.arange(9), 5)
print(Z)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [87]:
a=np.random.randint(0,1,20)
print(np.logical_not(a,out=a))
print(np.negative(a, out=a))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [88]:
def distance(P0,P1,p):
    t=P1 - P0
    l=(t**2).sum(axis=1)
    u=-((P0[:,0]-p[...,0])*t[:,0] + (P0[:,1]-p[...,1])*t[:,1]) / l
    u=u.reshape(len(u),1)
    d=P0+u*t-p
    return np.sqrt((d**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,( 1,2))
distance(P0, P1, p)

array([2.07e+00, 7.05e+00, 1.92e+01, 2.93e+00, 2.78e-03, 6.08e+00,
       6.16e+00, 7.37e+00, 6.56e+00, 5.05e+00])

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [89]:
np.array([distance(P0,P1,p_i) for p_i in p])


array([[2.07e+00, 7.05e+00, 1.92e+01, 2.93e+00, 2.78e-03, 6.08e+00,
        6.16e+00, 7.37e+00, 6.56e+00, 5.05e+00]])

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [90]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 7 0 7 5 9 9 1 3 5]
 [4 2 6 6 7 7 0 9 1 4]
 [9 2 2 0 2 7 3 2 2 2]
 [9 9 5 3 8 9 5 1 0 7]
 [2 7 1 8 9 4 4 4 2 5]
 [7 9 5 6 3 2 9 0 3 6]
 [4 8 5 1 2 9 4 8 6 7]
 [6 9 6 8 0 6 5 5 2 8]
 [6 2 3 4 4 4 1 9 6 9]
 [1 0 6 7 4 1 4 7 3 8]]
[[0 0 0 0 0]
 [0 0 7 0 7]
 [0 4 2 6 6]
 [0 9 2 2 0]
 [0 9 9 5 3]]


D:\Applications\Anaconda\lib\site-packages\ipykernel_launcher.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [91]:
Z=np.arange(1,15,dtype=np.uint32)
stride_tricks.as_strided(Z,(11,4),(4,4))

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=uint32)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [92]:
Z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(Z)
rank=np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [93]:
a=np.random.randint(1,10,5)
print(np.bincount(a))
np.bincount(a).argmax()

[0 0 2 0 1 1 0 0 1]


2

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [94]:
X=np.random.randint(0,5,(10,10))
n=3
i=1+(X.shape[0]-3)
j=1+(X.shape[1]-3)
C=stride_tricks.as_strided(X, shape=(i, j, n, n), strides=X.strides + X.strides)
print(C)

[[[[3 4 4]
   [0 4 1]
   [4 0 4]]

  [[4 4 3]
   [4 1 0]
   [0 4 4]]

  [[4 3 2]
   [1 0 1]
   [4 4 3]]

  [[3 2 1]
   [0 1 4]
   [4 3 3]]

  [[2 1 1]
   [1 4 4]
   [3 3 4]]

  [[1 1 1]
   [4 4 4]
   [3 4 4]]

  [[1 1 3]
   [4 4 3]
   [4 4 0]]

  [[1 3 2]
   [4 3 3]
   [4 0 1]]]


 [[[0 4 1]
   [4 0 4]
   [2 1 1]]

  [[4 1 0]
   [0 4 4]
   [1 1 2]]

  [[1 0 1]
   [4 4 3]
   [1 2 0]]

  [[0 1 4]
   [4 3 3]
   [2 0 4]]

  [[1 4 4]
   [3 3 4]
   [0 4 3]]

  [[4 4 4]
   [3 4 4]
   [4 3 2]]

  [[4 4 3]
   [4 4 0]
   [3 2 1]]

  [[4 3 3]
   [4 0 1]
   [2 1 1]]]


 [[[4 0 4]
   [2 1 1]
   [3 2 0]]

  [[0 4 4]
   [1 1 2]
   [2 0 2]]

  [[4 4 3]
   [1 2 0]
   [0 2 4]]

  [[4 3 3]
   [2 0 4]
   [2 4 3]]

  [[3 3 4]
   [0 4 3]
   [4 3 4]]

  [[3 4 4]
   [4 3 2]
   [3 4 2]]

  [[4 4 0]
   [3 2 1]
   [4 2 1]]

  [[4 0 1]
   [2 1 1]
   [2 1 3]]]


 [[[2 1 1]
   [3 2 0]
   [0 1 3]]

  [[1 1 2]
   [2 0 2]
   [1 3 0]]

  [[1 2 0]
   [0 2 4]
   [3 0 2]]

  [[2 0 4]
   [2 4 3]
   [0 2 4]]

  [[0 4 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [95]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)
X = symetric(np.random.randint(0,10,(5,5)))
X[2,3] = 42
print(X)

[[ 1 15  5  6  6]
 [15  9  9  6  7]
 [ 5  9  7 42  4]
 [ 6  6 42  1  4]
 [ 6  7  4  4  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [96]:
p,n= 10, 20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
X=np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(X)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [97]:
Z=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [98]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(50,50))
for i in range(10): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [99]:
Z = np.arange(150)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[145 146 147 148 149]
[148 149 147 146 145]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [100]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [101]:
x=np.array([("hello",2.5,3),
            ("karthick",3.6,2)])
r=np.core.records.fromarrays(x.T,names='col1,col2,col3',formats='S8,f8,i8')
print(r)

[(b'hello', 2.5, 3) (b'karthick', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [102]:
x=np.random.random(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.63 s ± 73.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
378 ms ± 50.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
178 ms ± 13.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [103]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[..., np.newaxis, np.newaxis] == B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 3 4 5 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [104]:
M=np.random.randint(0,5,(10,3))
print(M)
E=np.all(M[:,1:] == M[:,:-1], axis=1)
U=M[~E]
print(U)
U=M[M.max(axis=1) != M.min(axis=1),:]
print(U)

[[0 4 0]
 [4 1 0]
 [1 1 4]
 [0 3 1]
 [1 4 1]
 [0 4 0]
 [4 0 1]
 [2 1 3]
 [4 2 4]
 [1 0 1]]
[[0 4 0]
 [4 1 0]
 [1 1 4]
 [0 3 1]
 [1 4 1]
 [0 4 0]
 [4 0 1]
 [2 1 3]
 [4 2 4]
 [1 0 1]]
[[0 4 0]
 [4 1 0]
 [1 1 4]
 [0 3 1]
 [1 4 1]
 [0 4 0]
 [4 0 1]
 [2 1 3]
 [4 2 4]
 [1 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [105]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [107]:
Z = np.random.randint(0,21(5,5))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
round(print(uZ))

TypeError: 'int' object is not callable

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [108]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.35, 0.31, 0.47, 0.26, 0.39, 0.58, 0.21, 0.74, 0.49, 0.11],
       [0.29, 0.26, 0.39, 0.22, 0.33, 0.48, 0.17, 0.62, 0.41, 0.09],
       [0.3 , 0.27, 0.4 , 0.22, 0.33, 0.49, 0.18, 0.63, 0.42, 0.1 ],
       [0.03, 0.03, 0.05, 0.03, 0.04, 0.06, 0.02, 0.07, 0.05, 0.01],
       [0.14, 0.13, 0.19, 0.11, 0.16, 0.24, 0.08, 0.3 , 0.2 , 0.05],
       [0.11, 0.1 , 0.15, 0.08, 0.13, 0.19, 0.07, 0.24, 0.16, 0.04],
       [0.18, 0.16, 0.24, 0.13, 0.2 , 0.3 , 0.11, 0.38, 0.25, 0.06],
       [0.19, 0.17, 0.26, 0.14, 0.22, 0.32, 0.11, 0.41, 0.27, 0.06],
       [0.23, 0.2 , 0.31, 0.17, 0.25, 0.38, 0.13, 0.48, 0.32, 0.07],
       [0.16, 0.15, 0.22, 0.12, 0.18, 0.27, 0.1 , 0.35, 0.23, 0.05]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [109]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [110]:
X=np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n=4
M=np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M&=(X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [111]:
X=np.random.randn(100) 
N=1000 
idx=np.random.randint(0, X.size, (N, X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means, [2.5, 97.5])
print(confint)

[-0.34  0.08]
